language: julia

os:
  - linux
# - osx

julia:
  - 1.3
  - 1.4
  - 1.5
  - nightly

notifications:
  email: false

before_install:
  - sudo apt-get install -y saods9 xpa-tools libxpa-dev

# To test this package, an X server must be running.
services:
  - xvfb

codecov: true

coveralls: true

jobs:
  allow_failures:
    - os: osx
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.build("SAOImageDS9");
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
