language: julia

os:
  - linux
# - osx

julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
    - os: osx
    - julia: nightly

notifications:
  email: false

before_install:
  - sudo apt-get install -y saods9 xpa-tools libxpa-dev

# To test this package, an X server must be running.
services:
  - xvfb

# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'if VERSION >= v"0.7.0-DEV.5183"; using Pkg; end;
#                                 Pkg.clone("https://github.com/JuliaAstro/XPA.jl");
#                                 Pkg.clone(pwd());
#                                 Pkg.test("DS9"; coverage=true)'
  - julia --check-bounds=yes -e 'println("Starting DS9...");
                                 proc = run(`/usr/bin/ds9 -xpa yes`; wait=false);
                                 if VERSION >= v"0.7.0-DEV.5183"; using Pkg; end;
                                 Pkg.clone("https://github.com/JuliaAstro/XPA.jl");
                                 Pkg.clone(pwd());
                                 println("Killing DS9...");
                                 kill(proc)'

after_success:
  - julia --project=coverage/ -e 'if VERSION >= v"0.7"; using Pkg; Pkg.instantiate(); end'
  - julia --project=coverage/ coverage/coverage.jl

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.clone("https://github.com/JuliaAstro/XPA.jl");
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();'
        - julia --project=docs/ docs/make.jl
      after_success: skip
