name = "DS9"
uuid = "dbce9b26-8eb4-4825-964b-d4940cf8daff"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr>"]
version = "0.2.0"

[deps]
XPA = "d310a076-6a08-52b6-ab78-79baa254182b"

[compat]
julia = "1.3"
XPA = "0.2"
